// ignore_for_file: constant_identifier_names
const String STOCK_SIZE = "m";

const List<String> STOCK_IMAGES = [
  "https://i.imgur.com/0M3svbl$STOCK_SIZE.png",
  "https://i.imgur.com/TyjYbdf$STOCK_SIZE.png",
  "https://i.imgur.com/OIuqDXh$STOCK_SIZE.png",
  "https://i.imgur.com/8fiKNTz$STOCK_SIZE.png",
  "https://i.imgur.com/f5cHJ9x$STOCK_SIZE.png",
  "https://i.imgur.com/gSn3ChQ$STOCK_SIZE.jpg",
  "https://i.imgur.com/G0ZqXDY$STOCK_SIZE.jpg",
  "https://i.imgur.com/B0sPFK5$STOCK_SIZE.jpg",
  "https://i.imgur.com/I96cCUZ$STOCK_SIZE.jpg",
  "https://i.imgur.com/DFRegDl$STOCK_SIZE.jpg",
  "https://i.imgur.com/l3y6WOz$STOCK_SIZE.jpg",
  "https://i.imgur.com/A23ojCq$STOCK_SIZE.jpg",
  "https://i.imgur.com/HdhhYWs$STOCK_SIZE.jpg",
  "https://i.imgur.com/SO9NdU4$STOCK_SIZE.jpg",
  "https://i.imgur.com/mGIDpgo$STOCK_SIZE.jpg",
  "https://i.imgur.com/HgQq1JW$STOCK_SIZE.jpg",
  "https://i.imgur.com/RGiVNv6$STOCK_SIZE.jpg",
  "https://i.imgur.com/ciVMSzI$STOCK_SIZE.jpg",
  "https://i.imgur.com/47IgTi8$STOCK_SIZE.jpg",
  "https://i.imgur.com/5U11opp$STOCK_SIZE.jpg",
  "https://i.imgur.com/Vw4ncDX$STOCK_SIZE.jpg",
  "https://i.imgur.com/7IHbJgw$STOCK_SIZE.jpg",
  "https://i.imgur.com/z2Ji5Oq$STOCK_SIZE.jpg",
  "https://i.imgur.com/CQ7C0lc$STOCK_SIZE.jpg",
  "https://i.imgur.com/PEQWMRh$STOCK_SIZE.jpg",
  "https://i.imgur.com/fumzPRK$STOCK_SIZE.jpg",
  "https://i.imgur.com/AB57bc8$STOCK_SIZE.jpg",
  "https://i.imgur.com/BZyToXk$STOCK_SIZE.jpg",
  "https://i.imgur.com/tRFZl38$STOCK_SIZE.jpg",
  "https://i.imgur.com/A9tQXCM$STOCK_SIZE.jpg",
  "https://i.imgur.com/NrTQmZv$STOCK_SIZE.jpg",
  "https://i.imgur.com/hE0EW6V$STOCK_SIZE.jpg",
  "https://i.imgur.com/itZ7Nh3$STOCK_SIZE.jpg",
];
