String size = "m";

List<String> stockImages = [
  "https://i.imgur.com/0M3svbl$size.png",
  "https://i.imgur.com/TyjYbdf$size.png",
  "https://i.imgur.com/OIuqDXh$size.png",
  "https://i.imgur.com/8fiKNTz$size.png",
  "https://i.imgur.com/f5cHJ9x$size.png",
  "https://i.imgur.com/gSn3ChQ$size.jpg",
  "https://i.imgur.com/G0ZqXDY$size.jpg",
  "https://i.imgur.com/B0sPFK5$size.jpg",
  "https://i.imgur.com/I96cCUZ$size.jpg",
  "https://i.imgur.com/DFRegDl$size.jpg",
  "https://i.imgur.com/l3y6WOz$size.jpg",
  "https://i.imgur.com/A23ojCq$size.jpg",
  "https://i.imgur.com/HdhhYWs$size.jpg",
  "https://i.imgur.com/SO9NdU4$size.jpg",
  "https://i.imgur.com/mGIDpgo$size.jpg",
  "https://i.imgur.com/HgQq1JW$size.jpg",
  "https://i.imgur.com/RGiVNv6$size.jpg",
  "https://i.imgur.com/ciVMSzI$size.jpg",
  "https://i.imgur.com/47IgTi8$size.jpg",
  "https://i.imgur.com/5U11opp$size.jpg",
  "https://i.imgur.com/Vw4ncDX$size.jpg",
  "https://i.imgur.com/7IHbJgw$size.jpg",
  "https://i.imgur.com/z2Ji5Oq$size.jpg",
  "https://i.imgur.com/CQ7C0lc$size.jpg",
  "https://i.imgur.com/PEQWMRh$size.jpg",
  "https://i.imgur.com/fumzPRK$size.jpg",
  "https://i.imgur.com/AB57bc8$size.jpg",
  "https://i.imgur.com/BZyToXk$size.jpg",
  "https://i.imgur.com/tRFZl38$size.jpg",
  "https://i.imgur.com/A9tQXCM$size.jpg",
  "https://i.imgur.com/NrTQmZv$size.jpg",
  "https://i.imgur.com/hE0EW6V$size.jpg",
  "https://i.imgur.com/itZ7Nh3$size.jpg",
];
